{
  "hash": "33a2c8c227966e481efc461ead3f5fe2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis diferencial de PTMs de la Histona H3 (9–17)\"\n---\n\n\n\n\n## Introducción\n\nA continuación presentan los resultados del flujo de trabajo estadístico integrado aplicado a las PTMs del fragmento H3(9–17), combinando tres marcos complementarios: modelos lineales moderados con limma sobre datos transformados mediante CLR [@smyth2004; @smyth2005], modelos binomiales negativos con edgeR sobre conteos normalizados mediante TMM [@robinson2010] y el enfoque limma‑voom sobre log2‑CPM con pesos de precisión [@law2014]. A partir de la misma matriz de seis muestras (tres asíncronas y tres mitóticas) y veinte proteoformas, se modelan contrastes mitosis vs asincronía bajo supuestos distintos —normal moderada, binomial negativa con dispersión moderada y voom como puente entre ambos— lo que permite evaluar la robustez de los cambios detectados y la sensibilidad de cada enfoque a la heterocedasticidad y a la baja replicación biológica.\n\nEn las secciones siguientes se describen, primero, los resultados diferenciales obtenidos por cada pipeline (coeficientes de cambio, significancia ajustada y patrones globales en volcano plots y heatmaps) y, después, la comparación cuantitativa entre métodos mediante correlación de logFC, distribución de PTMs significativas y medidas de solapamiento como el índice de Jaccard. Este análisis integrado permite identificar un núcleo de PTMs diferencialmente reguladas de forma consistente entre limma‑CLR, limma‑voom y edgeR, en particular aquellas asociadas a fosforilación en S10 y sus combinaciones con acetilación en K14, y valorar qué discrepancias son atribuibles a diferencias de modelización estadística más que a ruido biológico [@sartor2006; @law2014; @robinson2010]\n\n## Análisis diferencial de PTMs del Fragmento H3(9–17)\n\nA partir del conjunto de datos composicional descrito en el capítulo anterior y del análisis exploratorio previo (incluyendo el heatmap y la agrupación de muestras por estado celular), en este capítulo se presentan los resultados del análisis diferencial mediante tres marcos estadísticos independientes: limma‑CLR, edgeR‑NB y limma‑voom.\n\nCada modelo se analiza de forma separada, describiendo el patrón de cambios en las proteoformas entre estados asincrónico y mitótico, y poniendo el foco en el número de PTMs significativas, la dirección y magnitud de los efectos estimados y la estabilidad de las conclusiones bajo supuestos estadísticos alternativos.\n\n\n\n### Modelo 1: limma-CLR\n\nLos datos de las distintas proteoformas son proporciones composicionales. Para romper la restricción de suma constante y proyectar los datos al espacio euclídeo, se aplica la transformación Centered Log-Ratio (CLR).\n\nPara cuantificar los cambios en las proporciones de proteoformas entre estados asincrónico y mitótico se aplicó un modelo lineal moderado con `limma` sobre la matriz CLR, con una parametrización sencilla (intercepto + contraste mitótico) y moderación empírico‑bayesiana dependiente de la intensidad (IBMT)\n\n\n\n\n::: {#tbl-result-limma .cell tbl-cap='Coeficientes de cambio (logFC), estadístico t y valor ajustado de p (FDR) obtenidos con el modelo limma‑CLR para cada proteoforma de H3(9–17) en el contraste mitótico vs asincrónico.'}\n::: {.cell-output-display}\n\n\n|                |  logFC|       t| adj.P.Val|\n|:---------------|------:|-------:|---------:|\n|K9me1K14ac      | -2.029| -10.597|     0.000|\n|K14ac           | -2.148|  -8.605|     0.000|\n|K9me1           | -1.978|  -7.836|     0.000|\n|K9me3           | -2.373|  -7.202|     0.000|\n|unmod           | -2.134|  -6.893|     0.000|\n|K9me2S10ph      |  2.484|   6.533|     0.000|\n|K9me2S10phK14ac |  2.265|   5.171|     0.000|\n|K9me2           | -1.886|  -5.030|     0.000|\n|K9me3K14ac      | -1.930|  -4.601|     0.000|\n|K9me1S10ph      |  3.662|   4.588|     0.000|\n|K9me3S10ph      |  1.607|   4.500|     0.000|\n|S10phK14ac      |  3.936|   4.486|     0.000|\n|S10ph           |  2.175|   4.472|     0.000|\n|K9me2K14ac      | -1.877|  -5.154|     0.001|\n|K9acK14ac       | -3.282|  -4.151|     0.001|\n|K9me3S10phK14ac |  1.851|   3.540|     0.003|\n|K9acS10ph       |  1.811|   2.498|     0.026|\n|K9me1S10phK14ac |  2.457|   2.423|     0.029|\n|K9ac            | -1.974|  -2.394|     0.029|\n|K9acS10phK14ac  | -0.637|  -0.870|     0.396|\n\n\n:::\n:::\n\n\nEn la @tbl-result-limma se presentan los resultados del análisis realizado mediante `limma`, para la que $\\text {logFC}$ corresponde al logaritmo en base 2 del cociente entre las coordenadas CLR de la misma marca en estado asíncrono y el mitítio, **t** al estasístico t de Student moderado y **adj.P.val** al valpr de p ajustado con el algoritmo de Benjamini-Hochberg (BH) para controlar la Tasa de Descubrimiento Falso (FDR). Como puede verse, hay evidencia estadística suficiente para rechazar la hipótesis nula de igualdad de abundancias relativas entre la condición asíncrona y la mitótica casi de las proteoformas estudiadas ($\\text{FDR} < 0.05$).\n\nEl análisis de estos resultados sitúa a la doble modificación S10phK14ac en el máximo absoluto de enriquecimiento en la mitosis con un coeficiente de $3.936$, seguida de cerca por K9me1S10ph ($\\text{logFC} = 3.662$). En el extremo opuesto, la mayor disminución relativa se registra en la forma acetilada K9acK14ac ($\\text{logFC} = -3.282$). Finalmente, se puede ver que K9acS10phK14ac constituye la única excepción de todo el fragmento, mostrando un cambio marginal ($\\text{logFC} = -0.637$) y un valor de p ajustado no significativo ($\\text{adj.P.Val} = 0.396$).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Volcano plot de los coeficientes de cambio (logFC) obtenidos mediante limma tras transformación CLR e inferencia con IBMT. El eje X representa el logFC, mientras que el eje Y muestra la significancia estadística como –log10 del valor ajustado de p. Las PTMs significativas (FDR < 0.05) se destacan en rojo, facilitando la identificación visual de modificaciones diferencialmente reguladas.](32_resultados_bioinfo_files/figure-pdf/fig-volcanolima-1.pdf){#fig-volcanolima}\n:::\n:::\n\n\nEn la @fig-volcanolima se observa que la gran mayoría de las proteoformas no fosforiladas se sitúan en el cuadrante superior izquierdo, mostrando coeficientes de cambio negativos pronunciados. En en el cuadrante superior derecho, se agrupan, algo más concentradas, casi todas las variantes que portan la fosforilación en la Serina 10 (S10ph), reflejando magnitudes de cambio positivas y homogéneas. Finalmente, se puede ver que K9acS10phK14ac constituye la única excepción visual de todo el espacio bidimensional, posicionándose de forma aislada por debajo del umbral de significancia estadística (línea horizontal discontinua) y en una zona adyacente al origen del cambio.\n\n### Modelo 2: edgeR-NB\n\nComo enfoque alternativo basado en conteos, se aplicó `edgeR` modelando las abundancias de las proteoformas mediante una distribución binomial negativa. A partir de los pseudo-conteos (obtenidos multiplicando las abundancias relativas por un factor de $10^6$) y del factor de grupo, se construyó un objeto DGEList y se aplicó la normalización TMM (Trimmed Mean of M-values) para corregir los efectos de composición entre muestras [@robinson2010] . En nuestro caso los valores M corresponden al $log_2$ del cociente de abundancias entre las abundancias en asíncrono y en mitosis. Posteriormente, se ajustó un modelo lineal generalizado cuasi-verosímil (NB-QLGLM) para evaluar el efecto de la condición mitótica sobre cada proteoforma mediante el test F de cuasi-verosímil (QLF).\n\n\n\n\n::: {#tbl-resultedge .cell tbl-cap='Resultados del ajuste del modelo edgeR-NB'}\n::: {.cell-output-display}\n\n\n|                |  logFC|       F| PValue|\n|:---------------|------:|-------:|------:|\n|K9me2S10ph      |  5.848| 168.693|  0.000|\n|K9me3S10ph      |  4.552|  97.685|  0.000|\n|K9me2S10phK14ac |  5.461|  82.335|  0.000|\n|K9me3S10phK14ac |  4.944|  65.697|  0.000|\n|S10ph           |  5.800|  45.637|  0.000|\n|S10phK14ac      |  7.873|  40.683|  0.000|\n|K9me1S10ph      |  7.214|  39.407|  0.000|\n|K9acS10ph       |  8.509|  19.962|  0.002|\n|K9me1S10phK14ac |  6.049|  16.310|  0.003|\n|unmod           | -0.858|   8.988|  0.014|\n|K14ac           | -0.839|   8.759|  0.015|\n|K9acK14ac       | -2.301|   8.454|  0.017|\n|K9me3           | -1.053|   8.064|  0.019|\n|K9me1           | -0.629|   3.792|  0.082|\n|K9me1K14ac      | -0.656|   3.708|  0.085|\n|K9acS10phK14ac  |  2.105|   2.978|  0.117|\n|K9me2           | -0.376|   1.498|  0.251|\n|K9ac            | -1.017|   0.905|  0.365|\n|K9me2K14ac      | -0.409|   0.860|  0.377|\n|K9me3K14ac      | -0.441|   0.625|  0.449|\n\n\n:::\n:::\n\n\nComo se puede ver en la @tbl-resultedge, para la doble modificación K9acS10ph se obtiene el máximo absoluto de enriquecimiento en mitosis bajo el modelo de conteos *edgeR.NB*, con un coeficiente de $8.510$, seguida muy de cerca por S10phK14ac ($\\text{logFC} = 7.874$). En el extremo opuesto, la mayor tasa de disminución relativa se registra en la forma acetilada K9acK14ac ($\\text{logFC} = -2.302$). Finalmente, la tabla permite identificar que K9acS10phK14ac constituye la única marca que incorpora el grupo fosfato pero no alcanza significancia estadística, mostrando un cambio moderado ($\\text{logFC} = 2.103$) pero un valor de p no significativo ($\\text{PValue} = 0.120$).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Volcano plot de los coeficientes de cambio (logFC) obtenidos mediante edgeR tras transformación CLR e inferencia con IBMT. El eje X representa el logFC, mientras que el eje Y muestra la significancia estadística como –log10 del valor ajustado de p. Las PTMs significativas (FDR < 0.05) se destacan en rojo, facilitando la identificación visual de modificaciones diferencialmente reguladas.](32_resultados_bioinfo_files/figure-pdf/fig-volcanoedge-1.pdf){#fig-volcanoedge}\n:::\n:::\n\n\nEn la @fig-volcanoedge se puede ver como la gran mayoría de las proteoformas no fosforiladas se sitían en el cuadrante inferior izquierdo, mostrando efectos cercanos al origen o carentes de significancia estadística al ubicarse por debajo del umbral crítico (línea horizontal discontinua). En el extremo opuesto, el gráfico agrupa a casi todas las variantes que incorporan la fosforilación en la Serina 10 (S10ph) en el cuadrante superior derecho, reflejando magnitudes de cambio positivas notablemente elevadas y una alta significancia estadística en la condición mitótica. Finalmente, se puede ver que marcas exclusivamente acetiladas o metiladas muestran cambios mucho más discretos, consolidando a K9acK14ac como la única excepción de su grupo al registrar una depleción significativa, mientras que K9acS10phK14ac se posiciona de forma aislada como la única variante fosforilada para la que no se aprecia enriquecimiento mitótico significativo.\n\n### Modelo 3: voom-limma\n\nAdemás de los análisis basados en CLR con limma y en modelos NB‑GLM con edgeR, incorporamos ahora un enfoque adicional mediante voom-limma, que permite trabajar directamente sobre los recuentos normalizados con TMM y modelados mediante pesos de precisión [@law2014]. Este tercer análisis actúa como un entre ambos marcos, ya que combina la estructura de conteos propia de edgeR con el modelado lineal de limma. Su inclusión facilita evaluar la robustez de los efectos estimados y comprobar hasta qué punto las conclusiones se mantienen bajo transformaciones y supuestos estadísticos distintos.\n\n\n::: {#tbl-resultvoom .cell tbl-cap='Resultados del ajuste mediante voom-limma'}\n::: {.cell-output-display}\n\n\n|PTM             |  logFC|      t| adj.P.Val|\n|:---------------|------:|------:|---------:|\n|K9me2S10ph      |  5.857| 11.040|     0.000|\n|K9me3S10ph      |  4.583|  9.292|     0.000|\n|K9me2S10phK14ac |  5.544|  9.082|     0.000|\n|K9me3S10phK14ac |  4.954|  8.336|     0.000|\n|K9acS10ph       |  7.490|  5.659|     0.002|\n|K9me1S10ph      |  7.742|  5.247|     0.003|\n|S10phK14ac      |  8.331|  4.935|     0.003|\n|S10ph           |  5.422|  4.194|     0.008|\n|K9acK14ac       | -2.509| -3.157|     0.028|\n|K9me3           | -1.157| -3.140|     0.028|\n|K14ac           | -0.821| -2.992|     0.032|\n|K9me1S10phK14ac |  6.057|  2.727|     0.044|\n|unmod           | -0.803| -2.595|     0.049|\n|K9me1K14ac      | -0.649| -2.032|     0.110|\n|K9me1           | -0.570| -1.726|     0.164|\n|K9me2           | -0.455| -1.405|     0.247|\n|K9acS10phK14ac  |  1.507|  1.203|     0.310|\n|K9me2K14ac      | -0.446| -0.989|     0.387|\n|K9me3K14ac      | -0.521| -0.955|     0.387|\n|K9ac            | -0.610| -0.526|     0.613|\n\n\n:::\n:::\n\n\nEn la @tbl-resultvoom se presentan los resultados obtenidos con el modelo híbrido *limma-voom*. Se aprecia que para la doble modificación K9me1S10ph se obtiene el máximo absoluto de enriquecimiento en mitosis con un coeficiente de 7.742, seguida muy de cerca por S10phK14ac ($\\text{logFC} = 8.331$). En el extremo opuesto, la mayor tasa de disminución relativa se registra en la forma acetilada K9acK14ac ($\\text{logFC} = -2.509$). Finalmente, la tabla permite identificar que K9acS10phK14ac constituye la única marca que incorpora el grupo fosfato pero no alcanza significancia estadística, mostrando un cambio moderado ($\\text{logFC} = 1.507$) pero un valor de p ajustado no significativo ($\\text{adj.P.Val} = 0.310$).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Volcano plot del análisis limma‑voom aplicado a los recuentos normalizados mediante TMM. El eje X muestra los logFC estimados sobre log2‑CPM con pesos de precisión, mientras que el eje Y representa la significancia estadística como –log10(p‑value). Las PTMs con adj.p.val < 0.05 se destacan en rojo.](32_resultados_bioinfo_files/figure-pdf/fig-limmavoon-1.pdf){#fig-limmavoon}\n:::\n:::\n\n\nLa @fig-limmavoon refleja de forma muy clara el patrón cuantificado en la @tbl-resultvoom: las proteoformas con fosforilación en S10 se concentran en el cuadrante superior derecho, con logFC positivos elevados y valores de $log_{10}(\\text{FDR})$ por encima del umbral de significancia (línea discontinua), lo que indica un enriquecimiento robusto en mitosis. Por el contrario, las formas no fosforiladas significativas (K9acK14ac, K9me3, K14ac y unmod) se sitúan en el cuadrante superior izquierdo con logFC negativos de menor magnitud, mientras que el resto de proteoformas no fosforiladas se agrupan cerca del eje vertical y por debajo del umbral de significancia, como puntos negros. En conjunto, el gráfico confirma que voom‑limma recupera el mismo núcleo de PTMs reguladas que los otros modelos, con fuertes aumentos en las formas S10ph y descensos más moderados en las marcas exclusivamente acetiladas o metiladas.\n\n## Comparación de los modelos\n\nAunque se parte formulaciones matemáticas y supuestos distribución de probalibilidad diferentes, los tres enfoques aplicados (*limma-CLR*, *edgeR-NB* y *voom-limma*) comparten una estructura jerárquica subyacente orientada a la mitigación del impacto de la baja replicación biológica ($n=3$):\n\n- **limma** modera la varianza de los residuos (datos continuos).\n\n- **edgeR** modera la dispersión de la binomial negativa (conteos).\n\n- **voom-limma** estima pesos de precisión a partir de la tendencia media-varianza para aplicar el modelo lineal a los conteos.\n\nTodos ellos aplican de forma común:\n\n- *Shrinkage* o encogimiento empírico-bayesiano compartiendo información entre proteoformas.\n\n- Ajuste de una tendencia media-varianza suavizada.\n\n- Aumento de los grados de libertad efectivos en los contrastes.\n\n- Control de la tasa de falso descubrimiento (FDR) mediante el método de Benjamini-Hochberg.\n\n\n\n### Tamaño del efecto\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Matriz de comparación analítica de los coeficientes de cambio (logFC) estimados para las proteoformas de H3(9–17) bajo los tres marcos estadísticos. La diagonal muestra la densidad estimada de los efectos; la mitad inferior presenta los gráficos de dispersión bivariados con su línea de ajuste lineal (rojo) frente a la línea de identidad (gris discontinuo); la mitad superior indica el coeficiente de correlación de Pearson (r).](32_resultados_bioinfo_files/figure-pdf/fig-comparacion-logfc-1.pdf){#fig-comparacion-logfc width=100%}\n:::\n:::\n\n\nPara evaluar la consistencia y dirección del tamaño del efecto obtenido con los tres modelos, la @fig-comparacion-logfc integra la distribución y correlación cruzada de los coeficientes $\\text{logFC}$.Se aprecia una concordancia en la direccion de los resultados de los tres modelos y una correlación lineal alta, con coeficientes de Pearson de $r = 0.974$ entre limma-CLR y edgeR-NB, $r = 0.988$ entre limma-CLR y limma-voom, y un máximo de $r = 0.996$ entre edgeR-NB y limma-voom. Las distribuciones de densidad reflejan un perfil bimodal idéntico en todos los modelos, dividiendo las proteoformas en dos bloques definidos que corresponden a al aumento relativo en la mitósis de las proteoformas foforiladas (S10ph) frente a la disminución de las variantes no fosforiladas. Los gráficos de dispersión revelan que las pendientes de ajuste lineal se desvían sistemáticamente por encima de la línea de identidad (gris discontinua) debido a un efecto de escala: la transformación geométrica composicional de limma-CLR restringe los coeficientes a un rango de $-3.2$ a $+3.9$, mientras que el modelo de conteos de edgeR amplifica drásticamente las magnitudes estimadas (alcanzando un máximo de $+8.51$) , dejando a limma-voom como el punto intermedio de dispersión óptimo (rango de $-2.5$ a $+8.3$).\n\n### Concordancia en la selección de proteoformas significativas\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagrama de Venn que cuantifica la intersección de las proteoformas identificadas como estadísticamente significativas (FDR < 0.05) por los marcos matemáticos analizados.](32_resultados_bioinfo_files/figure-pdf/fig-venn-ptms-1.pdf){#fig-venn-ptms width=100%}\n:::\n:::\n\n\nEl diagrama de Venn de la @fig-venn-ptms evalúa la concordancia en la selección de proteoformas significativas ($\\text{FDR} < 0.05$) obtenidas por los tres métodos estadísticos. El gráfico revela un solapamiento mayoritario entre las tres aproximaciones, donde el núcleo central concentra $13$ variantes comunes, representando el $68\\%$ del total de las proteoformas modificadas. Por su parte, la transformación composicional de *limma-CLR* es la única que detecta un bloque exclusivo de $6$ marcas adicionales ($32\\%$) que no alcanzan el umbral de significancia en los modelos basados en conteos. Finalmente, tanto *edgeR-NB* como *limma-voom* muestran una coincidencia absoluta entre sí ($0\\%$ de exclusividades individuales o compartidas por parejas fuera de la intersección global), confirmando que las diferencias estadísticas remanentes se limitan de manera exclusiva a la ganancia de sensibilidad observada en el espacio de proporciones trasformadas en coordenadas CLR.\n\nPara evaluar de manera cuantitativa la concordancia entre los métodos limma‑CLR, limma‑voom y edgeR, utilizamos el **índice de Jaccard**, una métrica ampliamente empleada en análisis ómicos para comparar conjuntos de elementos significativos. Este índice mide la proporción de coincidencia relativa entre dos métodos, calculando la fracción de PTMs compartidas respecto al total de PTMs detectadas por al menos uno de ellos. Su interpretación es directa: valores cercanos a 1 indican una coincidencia elevada, mientras que valores próximos a 0 reflejan solapamiento escaso.\n\nLos índices obtenidos, @tbl-jaccard, confirman de manera cuantitativa la concordancia de los modelos. Como se deduce del diagrama, la comparación entre limma-voom y edgeR-NB alcanza el máximo absoluto de identidad (Índice de Jaccard = 1.000), lo que demuestra una equivalencia a la hora de establecer el umbral de significancia bajo variables de conteo. Por su parte, las comparaciones cruzadas respecto al espacio composicional (limma-CLR vs limma-voom y limma-CLR vs edgeR-NB) convergen en un valor idéntico de 0.684, reflejando que la única divergencia radica en las 6 proteoformas que resultan estadísticamente significativas por mayor la sensibilidad de la transformación CLR.\n\n\n::: {#tbl-jaccard .cell tbl-cap='Cuantificación del solapamiento de conjuntos mediante el Índice de Jaccard normalizado.'}\n::: {.cell-output-display}\n\n\n|Comparación de Modelos  | Índice de Jaccard|\n|:-----------------------|-----------------:|\n|limma-CLR vs limma-voom |             0.684|\n|limma-CLR vs edgeR-NB   |             0.684|\n|limma-voom vs edgeR-NB  |             1.000|\n\n\n:::\n:::\n\n\nEn resumen, los resultados confirman que, a pesar de partir de supuestos de distribución de probablidad y transformaciones matemáticas distintas, los tres modelos convergen en un perfil bimodal idéntico que separa claramente las proteoformas según su estado de fosforilación en la Serina 10. La equivalencia casi perfecta entre edgeR-NB y limma-voom (Jaccard = 1.000), sumada a la detección de seis marcas exclusivas por parte de limma-CLR, demuestra que las escasas discrepancias entre métodos se limitan a diferencias de sensibilidad y no a contradicciones biológicas.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}